/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Collection of builds.
 */
class BuildListResult extends Array {
  /**
   * Create a BuildListResult.
   * @member {string} [nextLink] The URI that can be used to request the next
   * set of paged results.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of BuildListResult
   *
   * @returns {object} metadata of BuildListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BuildListResult',
      type: {
        name: 'Composite',
        className: 'BuildListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'BuildElementType',
                  type: {
                    name: 'Composite',
                    className: 'Build'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = BuildListResult;
