/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The result of a request to list container registry operations.
 */
class OperationListResult extends Array {
  /**
   * Create a OperationListResult.
   * @member {string} [nextLink] The URI that can be used to request the next
   * list of container registry operations.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of OperationListResult
   *
   * @returns {object} metadata of OperationListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'OperationListResult',
      type: {
        name: 'Composite',
        className: 'OperationListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'OperationDefinitionElementType',
                  type: {
                    name: 'Composite',
                    className: 'OperationDefinition'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = OperationListResult;
