/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The queue build request parameters.
 *
 */
class QueueBuildRequest {
  /**
   * Create a QueueBuildRequest.
   * @member {string} type Polymorphic Discriminator
   */
  constructor() {
  }

  /**
   * Defines the metadata of QueueBuildRequest
   *
   * @returns {object} metadata of QueueBuildRequest
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'QueueBuildRequest',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'type',
          clientName: 'type'
        },
        uberParent: 'QueueBuildRequest',
        className: 'QueueBuildRequest',
        modelProperties: {
          type: {
            required: true,
            serializedName: 'type',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = QueueBuildRequest;
