/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The properties of a response to source upload request.
 *
 */
class SourceUploadDefinition {
  /**
   * Create a SourceUploadDefinition.
   * @member {string} [uploadUrl] The URL where the client can upload the
   * source.
   * @member {string} [relativePath] The relative path to the source. This is
   * used to submit the subsequent queue build request.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SourceUploadDefinition
   *
   * @returns {object} metadata of SourceUploadDefinition
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SourceUploadDefinition',
      type: {
        name: 'Composite',
        className: 'SourceUploadDefinition',
        modelProperties: {
          uploadUrl: {
            required: false,
            serializedName: 'uploadUrl',
            type: {
              name: 'String'
            }
          },
          relativePath: {
            required: false,
            serializedName: 'relativePath',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SourceUploadDefinition;
